config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #  root "posts#index"
  get "filters", to: "filters#index"
  get "filters/meal", to: "filters#meal"
  get "filters/event", to: "filters#event"
  get "filters/occasion", to: "filters#occasion"
  get "filters/clarifications", to: "filters#clarifications"
  get "filters/budget_clarifications", to: "filters#budget_clarifications"
  get 'filters/user_clarification_choice', to: "filters#user_clarification_choice"
  get "filters/allergies", to: "filters#allergies"
  get "filters/location", to: "filters#location"
  get "filters/preferences", to: "filters#preferences"
  get "filters/budget", to: "filters#budget"

  get "restaurants/loading", to: "restaurants#loading"
  get "restaurants", to: "restaurants#index"
  get "restaurants/:id", to: "restaurants#show", as: :restaurant
  post "restaurants/:id", to: "saved_restaurants#create"

  resources :liked_restaurants, only: :create

  get "bills/new", to: "bills#new",  as: :new_bill
  post "bills", to: "bills#create"

  # resources :users, only: [:create, :new, :edit, :show, :update]
  get "users", to: "users#index"
  get "users/:id", to: "users#show", as: :user
  get "users/:id/edit", to: "users#edit", as: :edit_user
  patch "users/:id", to: "users#update"

  # get "saved_restaurants", to: "restaurants#saved"

  resources :saved_restaurants, only: :create
  # get "test_page", to: "pages#test_page"
  # get "2_test_page", to: "pages#2_test_page"
end

app/views/shared/_cards.html.erb
<div class="card-sll">
  <img class= "card-image" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-small-infos">
    <div>
      <h2><%= "restaurant.name" %></h2>
      <p><%= "Why you'll love it:" %></p>
      <p><%= "Price Per Person:" %></p>
      <p><%= "How others feel:" %></p>
    </div>
    <p><%= "why youll love" %></p>
    <p><%= "£" %></p>
    <p><%= "emoji" %></p>
  </div>
</div>


<%# <p><%= class="fa-solid fa-fire" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div style="height: 70px;"></div>
  <div class="navbar">
    <%= link_to root_path do %>
      <%= image_tag "new-house.png", class: "icons"%>
    <% end %>
    <%= link_to filters_path do %>
      <%= image_tag "cutlery-option.png", class: "icons" %>
    <% end %>
    <%= link_to new_bill_path do %>
      <%= image_tag "receipt-nav.png", class: "icons" %>
    <% end %>
    <%= link_to user_path(current_user) do %>
      <%= image_tag "user-icon.png", class: "icons" %>
    <% end %>

  </div>
<% end %>