config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #  root "posts#index"
  get "filters", to: "filters#index"
  get "filters/meal", to: "filters#meal"
  get "filters/event", to: "filters#event"
  get "filters/occasion", to: "filters#occasion"
  get "filters/clarifications", to: "filters#clarifications"
  get "filters/budget_clarifications", to: "filters#budget_clarifications"
  get 'filters/user_clarification_choice', to: "filters#user_clarification_choice"
  get "filters/allergies", to: "filters#allergies"
  get "filters/location", to: "filters#location"
  get "filters/preferences", to: "filters#preferences"
  get "filters/budget", to: "filters#budget"

  get "restaurants/loading", to: "restaurants#loading"
  get "restaurants", to: "restaurants#index"
  get "restaurants/:id", to: "restaurants#show", as: :restaurant
  post "restaurants/:id", to: "saved_restaurants#create"

  resources :liked_restaurants, only: :create

  get "bills/new", to: "bills#new",  as: :new_bill
  post "bills", to: "bills#create"

  # resources :users, only: [:create, :new, :edit, :show, :update]
  get "users", to: "users#index"
  get "users/:id", to: "users#show", as: :user
  get "users/:id/edit", to: "users#edit", as: :edit_user
  patch "users/:id", to: "users#update"

  # get "saved_restaurants", to: "restaurants#saved"

  resources :saved_restaurants, only: :create
  # get "test_page", to: "pages#test_page"
  # get "2_test_page", to: "pages#2_test_page"
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :restaurant_allergies
  has_many :allergies, through: :restaurant_allergies
  has_many :saved_restaurants
  has_many :users, through: :saved_restaurants
  # has_one_attached :pic_url
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index

    # if cookies[:location] == "positive" && cookies[:city].present? && cookies[:radius].present?
    #   # TODO: filter by location
    #   @restaurants = @restaurants.where(address: cookies[:city])
    # end

    # # Checking to see if preferences was selected
    # if cookies[:preferences] == "positive"

    #     # TODO: filter by wheat allergy
    #   @restaurants = @restaurants.where(wheat: cookies[:wheat]) if cookies[:wheat] == "positive"

    #     # TODO: filter by lactose allergy
    #   @restaurants = @restaurants.where(lactose: cookies[:lactose]) if cookies[:lactose] == "positive"


    #     # TODO: filter by nut allergy
    #   @restaurants = @restaurants.where(nuts: cookies[:nuts]) if cookies[:nuts] == "positive"


    #     # TODO: filter by vegetarian
    #   @restaurants = @restaurants.where(vegetarian: cookies[:vegetarian]) if cookies[:vegetarian] == "positive"
    # end


    # # TODO: filter by occasion
    # @restaurants = @restaurants.where(other_occasion: cookies[:occasion]) if cookies[:occasion].present?



    #   # TODO: filter by meal
    #   @restaurants = @restaurants.where(meal_type: cookies[:meal]) if cookies[:meal].present?


    # if cookies[:budget] == "positive" && cookies[:total_price].present? && cookies[:number_of_people].present?
    #   # TODO: filter by location
    #   @restaurants = @restaurants.where("(SELECT AVG(value::numeric) FROM UNNEST(budget) value) < ?", (cookies[:total_price].to_i))
    # end

    if cookies[:occasion].present? && cookies[:meal] == "dinner" && cookies[:wheat] == "positive"
      @restaurants = Restaurant.all
      @restaurants.where(other_occasion: cookies[:occasion], meal_type: cookies[:meal], wheat: cookies[:wheat])
    end

    if cookies[:filter] == "budget"
      @restaurants = Restaurant.where("(SELECT AVG(value::numeric) FROM UNNEST(budget) value) < ? AND meal_type = ?" , 20, cookies[:meal])
      # .where(meal_type: cookies[:meal]).where(address: cookies[:city])
      # @restaurants
    end


    @restaurants = @restaurants.first(5)

    # if params[:next_5].present?
    #   @restaurants = @restaurants.drop(5)
    #   params.delete :next_5
    # end

    @user = current_user


  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @user = current_user
  end

  def loading
    @restaurants = Restaurant.all
    if cookies[:location] == "positive" || cookies[:location] == "true"
      if params[:geolocation]
        cookies[:city] = params[:geolocation][:city]
        cookies[:radius] = params[:geolocation][:radius]
      end
    end
    # if params[:my_method][:wheat] == "positive"
    #   cookies[:wheat] = params[:my_method][:wheat]
    # end
    # if params[:my_method][:lactose] == "positive"
    #   cookies[:lactose] = params[:my_method][:lactose]
    # end
    # if params[:my_method][:nuts] == "positive"
    #   cookies[:nuts] = params[:my_method][:nuts]
    # end
    # if params[:my_method][:vegetarian] == "positive"
    #   cookies[:vegetarian] = params[:my_method][:vegetarian]
    # end
  end

  def saved
    @user = current_user
    @saved_restaurants = @user.saved_restaurants
  end
end

app/views/restaurants/_info_window.html.erb
<h2><%= restaurant.name %></h2>
<p><%= restaurant.address %></p>

app/views/restaurants/index.html.erb
<header class="header flex-shrink-0">
  <div class="name-number">
    <%# <%= link_to "MixEatUp", root_path %>
    <%# <p> 3 of 3</p> %>
  </div>
  <h1>5 Perfect Restaurants</h1>
</header>
<div class="container d-flex flex-column align-items-center justify-content-between row-gap-3 max-container-height my-3">
  <!-- <div class="cover mb-4 d-flex align-items-center justify-content-center">
    <div class="text-center text-black">
      <h3 class="typed-js" data-controller="typed-js"></h3>
    </div>
  </div> -->
  <div class="stimulus-container flex-grow-1 w-100" data-controller="swipe-restaurants">
    <div class="w-100 h-100 d-flex flex-column align-items-center justify-content-between gap-3" data-swipe-restaurants-target="mainCarousel">
      <%# <div class="d-flex align-items-center justify-content-between">
        <h3 class="mb-0 explore text-black">Explore</h3>
      </div> %>
      <div id="carouselExample" class="carousel slide w-100 h-100 px-5" data-swipe-restaurants-target="mainCarousel">
        <div class="carousel-inner h-100 w-100 py-3">
          <% @restaurants.each_with_index do |restaurant, index| %>
            <% active = index == 0 ? "active": "" %>
            <div class="carousel-item h-100 w-100 px-3 <%= active %>" id="<%= index %>" data-swipe-restaurants-target="carouselItem">
              <div class="card-small h-100 w-100" onclick="this.classList.toggle('flipped')">
                <div class="card-inner">
                  <div class="front d-flex flex-column align-items-center justify-content-between">






                    <%# <img src="https://img.freepik.com/premium-photo/delicious-details-closeup-food-table-with-purpose_950053-1523.jpg?size=626&ext=jpg&ga=GA1.1.1880011253.1699747200&semt=ais" class="carousel-card-img" /> %>
                    <%= image_tag restaurant.pic_url, class: "carousel-card-img", style: "max-height: 300px;" %>
                    <div class="card-small-infos flex-grow-1">
                      <div class="d-flex align-items-center justify-content-between">
                        <div class="card-nav">
                          <%= link_to saved_restaurants_path( {restaurant_id: restaurant.id}), data: {turbo_method: :post}, class: 'text-decoration-none' do %>
                            <i class="fa-regular fa-bookmark icon"></i>
                          <% end %>
                          <%= link_to liked_restaurants_path( {restaurant_id: restaurant.id}), data: {turbo_method: :post}, class: 'text-decoration-none' do %>
                            <i class="fa-regular fa-heart icon"></i>
                          <% end %>
                        </div>
                        <i class="fa-solid fa-circle-info" style="font-size: 34px; padding-right:10px;"></i>
                        <%# <i class="fa-solid fa-circle-info"></i> %>
                      </div>
                      <div></div>
                      <p class="back-title"><strong><%= restaurant.name  %></strong> <%= restaurant.trending %></p>
                      <div class="row">
                        <div class="col-6">
                          <h4><strong><%= "Cuisine: " %></strong><%= restaurant.cuisine_type %></h4>
                          <h4><strong><%= "Price: £" %></strong><%= (restaurant.budget.map {|budget| budget.to_i }).sum / restaurant.budget.length %>pp</h4>
                          <h4><strong><%= "How others feel: " %></strong><i class="fa-regular fa-face-smile"></i></h4>
                        </div>
                        <div class="col-6">
                          <h4><strong><%= "Why you'll love it: " %></strong><%= restaurant.about %></h4>
                        </div>
                        <div class="col-6">
                        </div>
                      </div>
                    </div>






                  </div>
                  <div class="back d-flex flex-column align-items-center justify-content-between">
                    <img src="https://img.freepik.com/premium-photo/delicious-details-closeup-food-table-with-purpose_950053-1523.jpg?size=626&ext=jpg&ga=GA1.1.1880011253.1699747200&semt=ais" class="carousel-card-img" />
                    <div class="card-small-infos flex-grow-1">
                      <p class="back-title"><%= restaurant.name  %> <%= restaurant.trending %></p>
                      <div class="row">
                        <div class="col-12">
                          <p class="contact-socials mb-0"><%= "How to contact: " %> <i class="fa-regular fa-envelope"></i> <i class="fa-solid fa-phone"></i> </p>
                        </div>
                        <div class="col-12">
                          <p class="contact-socials mb-0"><%= "Socials: " %> <i class="fa-brands fa-instagram"></i> <i class="fa-brands fa-facebook"></i> </p>
                        </div>
                        <div class="col-12">
                          <p class="information mb-0"><%= "Address: " %><%= restaurant.address %></p>
                        </div>
                        <div class="col-12">
                          <p class="information mb-0"><%= "Meals this restaurant is perfect for: " %><%= restaurant.meal_type %></p>
                        </div>
                        <div class="col-12">
                          <p class="information mb-0"><%= "Why you'll love it: " %><%= restaurant.reason %></p>
                        </div>
                        <div class="col-12">
                          <p class="information mb-0"><%= "Why you'll tell your friends about us tomorrow: " %><%= restaurant.about %></p>
                        </div>
                        <div class="col-12">
                          <p class="information mb-0"><%= "The WHY beind our restaurant choice: " %><%= restaurant.location_details %></p>
                        </div>
                        <div class="col-12">
                          <p class="information mb-0"><%= "Why you should bookmark me for later: " %><%= restaurant.other_occasion %></p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev" style="filter: invert(100%);">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next" style="filter: invert(100%);" data-action="click->swipe-restaurants#swipe">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    <div class="card-container d-none" data-swipe-restaurants-target="hiddenCarousel">
      <div class="d-flex align-items-center justify-content-between">
        <h3 class="mb-0 explore text-black">Explore</h3>
      </div>
      <div id="carouselExample1" class="carousel slide">
        <div class="carousel-inner">
          <div class="carousel-item"></div>
          <div class="carousel-item active">
            <%= link_to "Not found what you're looking for..click here for another 5", restaurants_path({next_5: true}), id: 'refresh-link' %>
          </div>
          <div class="carousel-item"></div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample1" data-bs-slide="prev" style="filter: invert(100%);" data-action="click->swipe-restaurants#swipeLeft">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample1" data-bs-slide="next" style="filter: invert(100%);">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
  </div>
</div>

<script>
  function flipCard(card) {
    card.classList.toggle("flipped");

     if (card.classList.contains("flipped")) {
      // Update the content of the back card
      var backContent = card.querySelector(".back");
      backContent.innerHTML = `<p>Here is more information</p>`;
    }
  }
</script>

app/views/restaurants/loading.html.erb
  <header class="header flex-shrink-0">
    <div class="name-number">
      <%# <%= link_to "MixEatUp", root_path%>
    </div>
    <h1>Summary</h1>
  </header>
  <div class="label" data-controller="loading-page" style="height:70dvh;">
    <h2 class= "calc">Calculating Your Perfect Matches</h2>
      <img class= "load" src="https://t3.ftcdn.net/jpg/04/44/58/26/360_F_444582608_qDpK9F0g0lPUtnvxe5ndlkRLIgZM8S45.jpg" alt="menu">
      <h2 class= "choice-bold">Your Choices:</h2>
      <ul class="container ml-5 mr-5 loading-list">
        <% if cookies[:meal].present? %>

        <li  ><span class="loading-bold">Meal: </span><%= cookies[:meal].capitalize %></li>
        <% end %>

        <% if cookies[:occasion].present? %>
        <li  ><span class="loading-bold">Occasion: </span><%= cookies[:occasion].capitalize %></li>
        <% end %>
        <% if cookies[:city].present?%>
        <li  ><span class="loading-bold">Location: </span><%= cookies[:city] %></li>
        <% end %>
        <% if cookies[:total_price].present? %>
        <li  ><span class="loading-bold">Total price: </span><%= cookies[:total_price] %></li>
        <% end %>
        <% if cookies[:number_of_people].present? %>
        <li  ><span class="loading-bold">Number of people: </span><%= cookies[:number_of_people] %></li>
        <% end %>
        <% if cookies[:wheat].present? %>
        <li  ><span class="loading-bold">Sensitivity: </span>Wheat</li>
        <% end %>
        <% if cookies[:lactose].present? %>
        <li  ><span class="loading-bold">Sensitivity: </span>Lactose</li>
        <% end %>
        <% if cookies[:nuts].present? %>
        <li  ><span class="loading-bold">Sensitivity: </span>Nuts</li>
        <% end %>
        <% if cookies[:vegetarian].present? %>
        <li  ><span class="loading-bold">Preferences: </span> Vegetarian</li>
        <% end %>
      </ul>
      <h2 data-loading-page-target="listItems" class= "d-none mt-5 pt-5"><span class="loading-bold">Loading </span>
        <span data-loading-page-target="listItems" class= "d-none">.</span>
        <span data-loading-page-target="listItems" class= "d-none">.</span>
        <span data-loading-page-target="listItems" class= "d-none">.</span>
      </h2>
</div>

app/views/restaurants/saved.html.erb
hello from restaurants-saved

app/views/restaurants/show.html.erb
<div class="position-relative">
  <div class="card-category card-large">
    <h1><%= @restaurant.name %></h1>

    <p>address: <%= @restaurant.address %></p>
    <p>cuisine_type: <%= @restaurant.cuisine_type %></p>
    <p>phone_no: <%= @restaurant.phone_no %></p>
    <p>chain: <%= @restaurant.chain %></p>
    <p>budget: <%= @restaurant.budget %></p>
    <p>opening_hour: <%= @restaurant.opening_hour %></p>
    <p>closing_hour: <%= @restaurant.closing_hour %></p>
    <p>meal_type: <%= @restaurant.meal_type %></p>
    <p>Why you'll tell your friends about us tomorrow: <%= @restaurant.reason %></p>
    <p>rating: <%= @restaurant.rating %></p>
    <p>trending: <%= @restaurant.trending %></p>
    <p>instagram: <%= @restaurant.instagram %></p>
    <p>facebook: <%= @restaurant.facebook %></p>
    <p>resy: <%= @restaurant.resy %></p>
    <p>The Why Behind Our Restaurant Choice: <%= @restaurant.about %></p>
    <p>Why You Should Bookmark Me For later: <%= @restaurant.location_details %></p>
    <p>Other occasion: <%= @restaurant.other_occasion %></p>

  </div>
</div>

<%# name:
address:
cuisine_type:
phone_no:
chain:
budget:
opening_hour:
closing_hour:
meal_type:
latitude:
longitude:
reason:
rating:
trending:
instagram:
facebook:
resy:
about:
location_details:
other_occasion: %>