config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #  root "posts#index"
  get "filters", to: "filters#index"
  get "filters/meal", to: "filters#meal"
  get "filters/event", to: "filters#event"
  get "filters/occasion", to: "filters#occasion"
  get "filters/clarifications", to: "filters#clarifications"
  get "filters/budget_clarifications", to: "filters#budget_clarifications"
  get 'filters/user_clarification_choice', to: "filters#user_clarification_choice"
  get "filters/allergies", to: "filters#allergies"
  get "filters/location", to: "filters#location"
  get "filters/preferences", to: "filters#preferences"
  get "filters/budget", to: "filters#budget"

  get "restaurants/loading", to: "restaurants#loading"
  get "restaurants", to: "restaurants#index"
  get "restaurants/:id", to: "restaurants#show", as: :restaurant
  post "restaurants/:id", to: "saved_restaurants#create"

  resources :liked_restaurants, only: :create

  get "bills/new", to: "bills#new",  as: :new_bill
  post "bills", to: "bills#create"

  # resources :users, only: [:create, :new, :edit, :show, :update]
  get "users", to: "users#index"
  get "users/:id", to: "users#show", as: :user
  get "users/:id/edit", to: "users#edit", as: :edit_user
  patch "users/:id", to: "users#update"

  # get "saved_restaurants", to: "restaurants#saved"

  resources :saved_restaurants, only: :create
  # get "test_page", to: "pages#test_page"
  # get "2_test_page", to: "pages#2_test_page"
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  def index
  end

  def occasion
    if params[:filter] == "occasion"
      cookies[:filter] = params[:filter]
    end
    redirect_to filters_budget_path if cookies[:filter] == "budget"
  end

  def meal
    if cookies[:filter] == "budget"
      cookies[:total_price] = params[:budget_form][:total_price]
      cookies[:number_of_people] = params[:budget_form][:number_of_people]
    end
    cookies[:occasion] = params[:occasion]
  end

  def clarifications
    cookies[:meal] = params[:meal]
    redirect_to filters_budget_clarifications_path if cookies[:filter] == "budget"
  end

  def budget_clarifications
    cookies[:meal] = params[:meal]
  end

  def user_clarification_choice
    choices = params[:user_clarifications]

    if choices[:budget] == "true"
      cookies[:budget] = "positive"
    else
      cookies[:budget] = "negative"
    end

    if choices[:preferences] == "true"
      cookies[:preferences] = "positive"
    else
      cookies[:preferences] = "negative"
    end

    if choices[:location] == "true"
      cookies[:location] = "positive"
    else
      cookies[:location] = "negative"

    end

      redirect_to filters_budget_path
  end

  def budget
    cookies[:filter] = "budget" if params[:filter] == "budget"
    redirect_to filters_preferences_path if cookies[:filter] == "occasion" && cookies[:budget] == "negative"
    # Need to check what these are doing

    redirect_to filters_preferences_path if cookies[:meal] == false

    # Need to check what these are doing
    if cookies[:filter] == "budget"
      cookies[:meal] = false
    end
  end


  def preferences
    # cookies.delete :total_price
    # cookies.delete :number_of_people
    # cookies.delete :drink_or_food_choice
    # This is only done when the user selects Budget at the beginning
    if cookies[:filter] == "budget"
      cookies[:preferences] = params[:user_clarifications][:preferences]
      cookies[:location] = params[:user_clarifications][:location]
      redirect_to filters_location_path if cookies[:preferences] == "0" || cookies[:preferences] != "true"
      return
    end
    if cookies[:budget] == "positive"
      cookies[:drink_or_food_choice] = "drinks" if params[:budget_form][:drinks] == "positive"
      cookies[:drink_or_food_choice] = "food" if params[:budget_form][:food] == "positive"
      cookies[:drink_or_food_choice] = "drinks and food" if params[:budget_form][:drink_and_food] == "positive"
    end

    if cookies[:budget] == "positive" && cookies[:filter] != "budget"
      cookies[:total_price] = params[:budget_form][:total_price]
      cookies[:number_of_people] = params[:budget_form][:number_of_people]
    # else
    #   cookies[:total_price] = "negative"
    #   cookies[:number_of_people] = "negative"
    end
    redirect_to filters_location_path if cookies[:preferences] == "negative" || cookies[:preferences] == "false"
  end

  def location
    cookies.delete :wheat
    cookies.delete :vegetarian
    cookies.delete :lactose
    cookies.delete :nuts
    if cookies[:filter] == "budget"
      if cookies[:preferences] == "true"
        cookies[:wheat] = params[:wheat] if params[:wheat] == "positive"
        cookies[:lactose] = params[:lactose] if params[:lactose] == "positive"
        cookies[:nuts] = params[:nuts] if params[:nuts] == "positive"
        cookies[:vegetarian] = params[:vegetarian] if params[:vegetarian] == "positive"
      end

      if cookies[:location] == "0" || cookies[:location] != "true"
        redirect_to restaurants_loading_path
      end
    end


    if cookies[:filter] == "occasion"
      if cookies[:preferences] == "positive"
        cookies[:wheat] = params[:wheat] if params[:wheat] == "positive"
        cookies[:lactose] = params[:lactose] if params[:lactose] == "positive"
        cookies[:nuts] = params[:nuts] if params[:nuts] == "positive"
        cookies[:vegetarian] = params[:vegetarian] if params[:vegetarian] == "positive"
      end
      if cookies[:location] == "negative"
        redirect_to restaurants_loading_path
      end
    end
    @restaurants = Restaurant.geocoded
    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        marker_html: render_to_string(partial: "marker") # Pass the restaurant to the partial
      }
    end
  end
end

app/views/filters/_marker.html.erb
<%= image_tag "map_pin2.png", height: 30, width: 30, alt: "Logo" %>

app/views/filters/allergies.html.erb
<%# ORIGINAL CODE %>
 <%# <%= simple_form_for :my_method, url: filters_location_path, method: :get do |f| %>
  <%# <%= f.input :wheat, as: :boolean, checked_value: "positive", unchecked_value: "negative" %>
  <%# <%= f.input :lactose, as: :boolean, checked_value: "positive", unchecked_value: "negative" %>
  <%# <%= f.input :nuts, as: :boolean, checked_value: "positive", unchecked_value: "negative"%>
  <%# <%= f.input :vegetarian, as: :boolean, checked_value: "positive", unchecked_value: "negative" %>
  <%# <%= f.button :submit %>
  <%# <%end%>

app/views/filters/budget.html.erb
<header class="header flex-shrink-0">
  <div class="name-number">
    <%# <%= link_to "MixEatUp", root_path%>


  </div>
  <h1>Budget</h1>
</header>

<div class="container d-flex flex-column align-items-center justify-content-between row-gap-3 max-container-height my-3" id="budget" >
  <div class="label">Bonjour! What budget parameters would you like to plan for in your culinary voyage?</div>
  <% if cookies[:filter] == "budget" %>
    <div class="label2">1. What do you plan to indulge in?</div>
    <%= simple_form_for :budget_form, url: filters_meal_path, method: :get, html: { class: 'w-100 h-100 d-flex flex-column align-items-center justify-content-between' } do |f| %>
      <div class="top-check-boxes d-flex justify-content-between pl-0 w-100 flex-grow-1">
        <%= f.input :drinks, as: :boolean, checked_value: 'positive', unchecked_value: 'negative', label_html: {class:"clickable-label drinks-image card-indulge drink-label flex-grow-1 h-100", onclick: "toggleCheckbox(this, 'drinks')"}, input_html: { class: "d-none" }, wrapper_html: { class: "flex-grow-1" } %>
        <%= f.input :food , as: :boolean,checked_value: 'positive', unchecked_value: 'negative', label_html: {class:"clickable-label food-image card-indulge food-label flex-grow-1 h-100", onclick: "toggleCheckbox(this, 'food')"}, input_html: { class: "d-none" }, wrapper_html: { class: "flex-grow-1" } %>
      </div>
      <%= f.input :drinks_and_food, as: :boolean,checked_value: 'positive', unchecked_value: 'negative',label_html: { class: "clickable-label food-and-drinks-image w-100 h-100 flex-grow-1 card-indulge drink-food-label", onclick: "toggleCheckbox(this, 'drinks_and_food')"},input_html: { class: "d-none" }, wrapper_html: { class: 'flex-grow-1 w-100' } %>


      <div class="label2">2. Let's set the perfect budget for your indulgent soiree!</div>
      <%= f.input :total_price, label: "What's your budget per person?", input_html: { type: 'number', class: 'w-100' }, wrapper_html: { class: 'w-100' } %>
      <%= f.input :number_of_people,label: "How many people will be attending?", input_html: { type: 'number', class: 'w-100' }, wrapper_html: { class: 'w-100' } %>
       <div class="d-flex align-items-center justify-content-center gap-4 my-2">
      <%= button_tag type: 'button', class: "left-button", onclick: "history.back();" do %>
        <i class="fa-solid fa-arrow-left"></i>
      <% end %>

       <% if cookies[:filter] == "occasion" && cookies[:preferences] == "positive" && cookies[:location] == "positive" %>
     <p class= "mb-0"> 1 of 3</p>
     <% elsif cookies[:filter] == "occasion" && (cookies[:preferences] == "positive" || cookies[:location] == "positive") %>
     <p class= "mb-0"> 1 of 2</p>
     <% elsif cookies[:filter] == "occasion" %>
     <p class= "mb-0"> 1 of 1</p>
     <% else %>
     <p class= "mb-0"> 2 of 4</p>
     <% end %>

      <%= f.button :button, type: :submit, class: "right-button", data: { buttons_target: "submit" } do %>
      <i class="fa-solid fa-arrow-right"></i>


      <% end %>
    </div>

    <% end %>

<!--   </div> -->

  <% else %>
    <div class="label2">1. What do you plan to indulge in?</div>
    <%= simple_form_for :budget_form, url: filters_preferences_path, method: :get, html: { class: 'w-100 h-100 d-flex flex-column align-items-center justify-content-between' } do |f|  %>
      <div class="top-check-boxes d-flex justify-content-between w-100 flex-grow-1">
        <%= f.input :drinks, as: :boolean, checked_value: 'positive', unchecked_value: 'negative', label_html: {class:"clickable-label drinks-image card-indulge h-100 drink-label", onclick: "toggleCheckbox(this, 'drinks')"},input_html: { class: "d-none" }, wrapper_html: { class: "flex-grow-1" } %>
        <%= f.input :food , as: :boolean,checked_value: 'positive', unchecked_value: 'negative', label_html: {class:"clickable-label food-image card-indulge h-100 food-label", onclick: "toggleCheckbox(this, 'food')"},input_html: { class: "d-none" }, wrapper_html: { class: "flex-grow-1" } %>
      </div>

      <%= f.input :drinks_and_food, as: :boolean,checked_value: 'positive', unchecked_value: 'negative',label_html: { class: "food-and-drinks-image h-100 w-100 card-indulge drink-food-label"},input_html: { class: "d-none" }, wrapper_html: { class: 'flex-grow-1 w-100' } %>
      <%= f.input :total_price, input_html: { type: 'number' }, wrapper_html: { class: 'w-100' } %>
      <%= f.input :number_of_people, input_html: { type: 'number' }, wrapper_html: { class: 'w-100' } %>

      <div class="d-flex align-items-center justify-content-center gap-4 my-2">
      <%= button_tag type: 'button', class: "left-button", onclick: "history.back();" do %>
        <i class="fa-solid fa-arrow-left"></i>
      <% end %>

       <% if cookies[:filter] == "occasion" && cookies[:preferences] == "positive" && cookies[:location] == "positive" %>
     <p class= "mb-0"> 1 of 3</p>
     <% elsif cookies[:filter] == "occasion" && (cookies[:preferences] == "positive" || cookies[:location] == "positive") %>
     <p class= "mb-0"> 1 of 2</p>
     <% elsif cookies[:filter] == "occasion" %>
     <p class= "mb-0"> 1 of 1</p>
     <% else %>
     <p class= "mb-0"> 2 of 4</p>
     <% end %>
      <%= f.button :button, type: :submit, class: "right-button", data: { buttons_target: "submit" } do %>
        <i class="fa-solid fa-arrow-right"></i>
      <% end %>
    </div>

    <% end %>

  <% end %>

</div>
<script>
  function toggleCheckbox(element, field) {
    // const parentElement = element.parentElement.parentElement.parentElement
    // const drinksCheckbox = parentElement.querySelector(`input[name="budget_form[drinks]"]`);
    // const foodCheckbox = parentElement.querySelector(`input[name="budget_form[food]"]`);
    // console.log(drinksCheckbox)
    // console.log(foodCheckbox)
    // if (field === 'drinks') {
    //   drinksCheckbox.value = "positive";
    //   drinksCheckbox.checked = true;
    //   foodCheckbox.checked = false;
    //   foodCheckbox.value = "negative";
    //   parentElement.querySelector('.drink-label').classList.add('selected');
    //   parentElement.querySelector('.food-label').classList.remove('selected');
    // } else if (field === 'food') {
    //   foodCheckbox.value = "positive";
    //   foodCheckbox.checked = true;
    //   drinksCheckbox.checked = false;
    //   drinksCheckbox.value = "negative";
    //   parentElement.querySelector('.drink-label').classList.remove('selected');
    //   parentElement.querySelector('.food-label').classList.add('selected');
    // }
    document.querySelectorAll('.clickable-label').forEach((el) => {
      el.classList.toggle('selected', el === element)
    })
  }
</script>

app/views/filters/budget_clarifications.html.erb
   <header class="header">
    <div class="name-number">
      <%# <%= link_to "MixEatUp", root_path%>
    </div>
    <h1>Final Details</h1>
  </header>


<div class="container d-flex flex-column align-items-center justify-content-between row-gap-3 max-container-height my-3">
  <div class="label">
    To place the finishing touches on your dining symphony, are there any crucial last-minute notes to <b>hit the right culinary crescendo?</b>
  </div>


<br>
  <%# <%=  form_for(:user_clarifications, url: filters_preferences_path, method: :get, data: {controller: "buttons"})  do |f| %>


  <%= form_for(:user_clarifications, url: filters_preferences_path, method: :get, data: {controller: "buttons"}, class: 'w-100  d-flex flex-column align-items-center justify-content-center row-gap-3 flex-grow-1')  do |f| %>


    <div class="card-clarification w-100" style="background-size:cover; background-position: center; background-image:linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url('<%= image_url('https://img.livestrong.com/640/cme-data/getty%2F999a2db907c849b6a162d2c843a8173d.jpg') %>');" data-field="preferences" data-action="click->buttons#selectButton" onclick="toggleCheckbox(this, 'preferences')">
      <div class="card-content ">
        <%= f.hidden_field :preferences, id: "preferences" %>
        <%= f.label :preferences, "Food Preferences" %>
      </div>
    </div>


    <div class="card-clarification w-100" style="background-size:cover; background-position: center; background-image:linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url('<%= image_url('https://images.france.fr/zeaejvyq9bhj/ic0lFVDFxxEKOycVSGLCO/a631fd4f1249538c53d5aaaa0f32078c/Header_Image_-Credit_-_Adobe_Ekaterina_Belova_v1.jpg') %>');"  data-field="location" data-action="click->buttons#selectButton" onclick="toggleCheckbox(this, 'location')">

      <div class="card-content">
        <%= f.hidden_field :location, id: "location" %>
        <%= f.label :location, "Location" %>
      </div>
    </div>


    <div class="d-flex align-items-center justify-content-center gap-4 my-2">
      <%= button_tag type: 'button', class: "left-button", onclick: "history.back();" do %>
        <i class="fa-solid fa-arrow-left"></i>
      <% end %>

      <p class="mb-0">4 of 4</p>

      <%= f.button :button, type: :submit, class: "right-button", data: { buttons_target: "submit" } do %>
      <i class="fa-solid fa-arrow-right"></i>

      <% end %>
    </div>
  <% end %>
</div>

<script>
  function toggleCheckbox(element, field) {
    const checkbox = element.querySelector(`input[name="user_clarifications[${field}]"]`);
    checkbox.value = !checkbox.value;
    checkbox.checked = !checkbox.checked;
    element.classList.toggle('selected', checkbox.checked);

  }
</script>

app/views/filters/budget_og.html.erb
<%= form_for :my_method, url: filters_meal_og_path, method: :get do |f|  %>
  <%= f.text_field :total_price_og, input_html: { type: 'number' } %>
  <%= f.text_field :number_of_people_og, input_html: { type: 'number' } %>
  <%= f.submit "Next" %>
<% end %>

app/views/filters/clarifications.html.erb
<header class="header">
  <div class="name-number">

    <%# <%= link_to "MixEatUp", root_path%>

  </div>
  <h1>Final Details</h1>
</header>

<div class="container d-flex flex-column align-items-center justify-content-between row-gap-3 max-container-height my-3">
  <div class="label">
    To place the finishing touches on your dining symphony, are there any crucial last-minute notes to <b>hit the right culinary crescendo?</b>
  </div>


  <%= form_for(:user_clarifications, url: filters_user_clarification_choice_path, method: :get, data: {controller: "buttons"}, class: 'w-100  d-flex flex-column align-items-center justify-content-center row-gap-3 flex-grow-1')  do |f| %>


    <div class="card-clarification w-100" style="background-size:cover; background-position: center;
    background-image:linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url('<%= image_url('https://i2-prod.mirror.co.uk/incoming/article30930935.ece/ALTERNATES/s615/0_Hands-with-bill-food-service-and-people-in-restaurant-customer-with-receipt-and-payment-with-cashi.jpg') %>');" data-field="budget" data-action="click->buttons#selectButton" onclick="toggleCheckbox(this, 'budget')">

      <div class="card-content">
        <%= f.hidden_field :budget, id: "budget" %>
        <%= f.label :budget, "Budget"%>
      </div>
    </div>

    <div class="card-clarification w-100" style="background-size:cover; background-position: center;
    background-image:linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url('<%= image_url('https://img.livestrong.com/640/cme-data/getty%2F999a2db907c849b6a162d2c843a8173d.jpg') %>');"
    data-field="preferences" data-action="click->buttons#selectButton"
    onclick="toggleCheckbox(this, 'preferences')">
      <div class="card-content ">
        <%= f.hidden_field :preferences, id: "preferences" %>
        <%= f.label :preferences, "Food Preferences" %>
      </div>
    </div>


    <div class="card-clarification w-100" style="background-size:cover; background-position: center; background-image:linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url('<%= image_url('https://images.france.fr/zeaejvyq9bhj/ic0lFVDFxxEKOycVSGLCO/a631fd4f1249538c53d5aaaa0f32078c/Header_Image_-Credit_-_Adobe_Ekaterina_Belova_v1.jpg') %>');"  data-field="location" data-action="click->buttons#selectButton" onclick="toggleCheckbox(this, 'location')">

      <div class="card-content">
        <%= f.hidden_field :location, id: "location" %>
        <%= f.label :location, "Location" %>
      </div>
    </div>


    <div class="d-flex align-items-center justify-content-center gap-4 my-2">
      <%= button_tag type: 'button', class: "left-button", onclick: "history.back();" do %>
        <i class="fa-solid fa-arrow-left"></i>
      <% end %>

      <p class="mb-0">4 of 4</p>

      <%= f.button :button, type: :submit, class: "right-button", data: { buttons_target: "submit" } do %>
        <i class="fa-solid fa-arrow-right"></i>
      <% end %>
    </div>
  <% end %>
</div>

<script>
  function toggleCheckbox(element, field) {
    const checkbox = element.querySelector(`input[name="user_clarifications[${field}]"]`);
    checkbox.value = !checkbox.value;
    checkbox.checked = !checkbox.checked;
    element.classList.toggle('selected', checkbox.checked);

  }
</script>

app/views/filters/clarifications_og.html.erb
<h1>Cookies to use for the filtering</h1>


<%= form_for :user_clarifications_og, url: filters_user_clarification_choice_og_path, method: :get  do |f| %>

  <%= f.label "Food preferences important?" %> <br />
  <%= f.check_box :preferences_og %> <br />
  <%= f.label "Location important?" %> <br />
  <%= f.check_box :location_og %> <br />

  <%= f.submit "Next" %>
<% end %>

<%
=begin%>

<%= simple_form_for :my_method, url: filters_budget_path, method: :get do |f|  %>
<%= f.input :budget, as: :boolean, checked_value: "positive", unchecked_value: "negative" %>
<%= f.input :preferences, as: :boolean, checked_value: "positive", unchecked_value: "negative" %>
<%= f.input :location, as: :boolean, checked_value: "positive", unchecked_value: "negative" %>
<%= f.button :submit %>
<% end %>
<%
=end%>

app/views/filters/event.html.erb
hello from filters event
<div class="card-get-started">
  <%= image_tag "dinner.jpeg", class: "dinner-pic" %>
  <div class="overlay-text">
    <%= link_to "Occasion", filters_occasion_path(:filter => :event)%>
  </div>
</div>

app/views/filters/index.html.erb
<header class="header flex-shrink-0">
  <div class="name-number">

    <%# <%= link_to "MixEatUp", root_path%>

  </div>
  <h1>Let's Get Started</h1>
</header>
<div class="container d-flex flex-column align-items-center justify-content-between row-gap-3 max-container-height my-3">
  <div class="card-get-started">
    <%= image_tag "dinner.jpeg", class: "dinner-pic" %>
    <div class="overlay-text">
      <%= link_to filters_occasion_path(filter: "occasion") do %>
        Occasion
        <p class="additional-text">Feeling lost in the quest for the perfect restaurant? Let us be your occasion matchmaker!</p>
      <% end %>
    </div>
  </div>

  <div class="card-get-started">
    <%= image_tag "pay_bill.jpeg", class: "budget-pic" %>
    <div class="overlay-text">
      <%= link_to filters_budget_path(filter: "budget") do %>
        Budget
        <p class="additional-text">Craving a night out but don't want to overspend - let us help you stay in budget and discover a spot quickly! </p>

      <% end %>

    </div>

    </div>

<div class="d-flex align-items-center justify-content-center gap-4 my-2">
      <%= button_tag type: 'button', class: "left-button", onclick: "history.back();" do %>
        <i class="fa-solid fa-arrow-left"></i>
      <% end %>

      <p class="mb-0">1 of 4</p>

      <%= button_tag type: 'button', class: "right-button", disabled: true do %>
        <i class="fa-solid fa-arrow-right"></i>
      <% end %>

    </div>
  </div>

app/views/filters/meal.html.erb
<header class="header flex-shrink-0">
  <div class="name-number">

    <%# <%= link_to "MixEatUp", root_path %>


  </div>
  <h1>Meals</h1>
</header>

<div class="container d-flex flex-column align-items-center justify-content-between row-gap-3 my-3 max-container-height">
  <div class="label">
    We certainly don't want to match you with a restaurant taking the day off. <b>When do you plan to dine?</b>
  </div>

  <div class="card-occasion w-100">
    <%= image_tag "pancakes.jpg", class: "occ-style" %>
    <div class="overlay-text">
      <% if cookies[:filter] == "budget"  %>
        <%=link_to  "Breakfast", filters_budget_clarifications_path(meal: "breakfast")  %>
      <% else %>
        <%=link_to  "Breakfast", filters_clarifications_path(meal: "breakfast")  %>
      <% end %>
    </div>
  </div>

  <div class="card-occasion w-100">
    <%= image_tag "Lobster.jpeg", class: "occ-style" %>
    <div class="overlay-text">
    <% if cookies[:filter] == "budget"  %>
      <%= link_to "Lunch", filters_budget_clarifications_path(meal: "lunch")  %>
    <% else %>
      <%= link_to "Lunch", filters_clarifications_path(meal: "lunch")  %>
    <% end %>
    </div>
  </div>


  <div class="card-occasion w-100">
    <%= image_tag "chicken.jpg", class: "occ-style" %>
    <div class="overlay-text">
      <% if cookies[:filter] == "budget"  %>
        <%=link_to "Dinner", filters_budget_clarifications_path(meal: "dinner")  %>
      <% else %>
        <%=link_to "Dinner", filters_clarifications_path(meal: "dinner")  %>
      <% end %>
    </div>
  </div>

  <div class="card-occasion w-100">
    <%= image_tag "cocktail3.jpg", class: "occ-style" %>
    <div class="overlay-text">
      <% if cookies[:filter] == "budget"  %>
        <%=link_to "Drinks", filters_budget_clarifications_path(meal: "drinks")  %>
      <% else %>
        <%= link_to "Drinks", filters_clarifications_path(meal: "drinks")  %>
      <% end %>
    </div>
  </div>

 <div class="d-flex align-items-center justify-content-center gap-4 my-2">
      <%= button_tag type: 'button', class: "left-button", onclick: "history.back();" do %>
        <i class="fa-solid fa-arrow-left"></i>
      <% end %>

      <p class="mb-0">3 of 4</p>

      <%= button_tag type: 'button', class: "right-button", disabled: true do %>
        <i class="fa-solid fa-arrow-right"></i>
      <% end %>

    </div>
</div>

app/views/filters/meal_og.html.erb
hello from meals
<button><%=link_to  "Breakfast", filters_clarifications_og_path(meal_og: "breakfast")  %></button>
<button><%=link_to "Lunch", filters_clarifications_og_path(meal_og: "lunch")  %></button>
<button><%=link_to "Dinner", filters_clarifications_og_path(meal_og: "dinner")  %></button>
<button><%=link_to "Drinks", filters_clarifications_og_path(meal_og: "drinks")  %></button>

app/views/filters/occasion.html.erb
<header class="header flex-shrink-0">
  <div class="name-number">
    <%# <%= link_to "MixEatUp", root_path%>
  </div>
  <h1>Occasion</h1>
</header>


<div class="container d-flex flex-column align-items-center justify-content-between row-gap-3 max-container-height my-3">
  <div class="label">
    Whether it's a soirée with friends, family outing or the thrilling premiere of a first date, <b>what's your occasion?</b>
  </div>



  <div class="card-occasion w-100">
      <%= image_tag "dayte.jpg", class: "occ-style" %>
    <div class="overlay-text">
      <%= link_to "Romantic", filters_meal_path(occasion: "romantic")%>
    </div>
  </div>


  <div class="card-occasion w-100">
    <%= image_tag "famdin.jpg", class: "occ-style" %>
    <div class="overlay-text">
      <%= link_to "Family", filters_meal_path(occasion: "family")%>
    </div>

  </div>

  <div class="card-occasion w-100">
    <%= image_tag "friends.jpeg", class: "occ-style" %>
    <div class="overlay-text">
      <%= link_to "Friends", filters_meal_path(occasion: "friends")%>
    </div>
  </div>

  <div class="card-occasion w-100">
    <%= image_tag "work.jpeg", class: "occ-style" %>
    <div class="overlay-text">
      <%= link_to "Work", filters_meal_path(occasion: "work")%>

    </div>

  </div>
<div class="d-flex align-items-center justify-content-center gap-4 my-2">
      <%= button_tag type: 'button', class: "left-button", onclick: "history.back();" do %>
        <i class="fa-solid fa-arrow-left"></i>
      <% end %>

      <p class="mb-0">2 of 4</p>

      <%= button_tag type: 'button', class: "right-button", disabled: true do %>
        <i class="fa-solid fa-arrow-right"></i>
      <% end %>

    </div>
</div>